### ISSUE TITLE
Multiple Overlapping Data-Types Per Item [HOW TO]

### ISSUE THREAD

**Issue by IsraelThompson** [razorjack/quicksand#100]
This isn't so much an issue, but more of a tip on how to achieve the above mentioned subject line.

I had the conundrum similar to those that have requested multiple select boxes/data types, except in my case I didn't need multiple select boxes and a major difference was that some of my items needed to overlap. For example, instead of everything being a simple cut and dry scenario like "Applications" and "Utilities", what if a couple of the items where both an Application and a Utility and you wanted them to show up in both lists if applicable?

I put together a quick example of a very easy way to achieve this without adding a bunch of extra data attributes/classes or unnecessarily cloning here:

http://jsfiddle.net/israelthompson/3smua/2/

Basically, in your list item markup, you list your categories delimited by spaces kind of like so:

`< li data-type='applications utilities'></ li>`

NOTE: `data-id` and other attributes may still be necessary for your finished product to work. I've only highlighted on `data-type` to simplify the example.

And in your jQuery code where you're filtering out the different lists, you add an tilde (~) to more or less convert your lookup from "equals" to "contains word". Example below:

`var $filteredData = $data.find('li[data-type~=' + $filterType.filter("input:checked").val() + ']')`

Our finished product making use of the method described above can be seen on our portfolio page linked to below:

http://dig-houston.com/portfolio

NOTE: Originally when I wrote this I was using the asterisk (*) instead of the tilde (~).

The asterisk works too, the only hitch with using it however, is that all of your categories must be distinguishable from the other — or unique. For instance "Monday Tuesday Wednesday Day" all contain the word "Day", thus might skew your results if you were looking for the word "Day" and your search is case-insensitive. So, the tilde, as pointed out by rhorbas in the comments below, became the better option.

Hope this helps someone out there.

**Comment by razorjack** [comment]
Looks like it's resolved :)
