### ISSUE TITLE
DO NOT MESS the width

### ISSUE THREAD

**Issue by ryh** [razorjack/quicksand#104]
responsive contents list
default `adjustWidth`  and it will be added width in style eg. `width:600px`  and responsive gone...

when `adjustWidth: false` , every time qucksand runs,it will add the `Width` with 2 X `padding`  px

**Comment by razorjack** [comment]
This is fixed in the latest version v1.6.0 – make sure to set `adjustWidth` to `false`. In the latest version, `false` doesn't set width to `auto`, it leaves this value alone.
