### ISSUE TITLE
Verticl menu?

### ISSUE THREAD

**Issue by AlchemyNow** [razorjack/quicksand#106]
I have a WP theme by a guy Who is using Quicksand and Pretty Foto. http://100.42.59.65/~twentyon/#featured-work  The client I am building this for wants two items.  1. a vertical sort menu and 2. pagination (because they have 100 videos.).

So, I have come here to see if anyone has an idea on how to change the menu from horizontal to vertical.  The theme developer says its beyone his ability.

Any help or guidane would be appreciated.

Aaron

**Comment by razorjack** [comment]
The only thing Quicksand does is animation. It doesn't even do filtering and sorting. It's up to website developer to filter, sort and call Quicksand in the right circumstances. Creating a vertical menu is not even a JavaScript issue – it's CSS which is way beyond the competence of the library. You'll need to find a developer who knows CSS but fortunately it should be a simple fix for even a moderately-skilled front-end developer.
