### ISSUE TITLE
Only works with jQuery 1.8.3, nothing higher

### ISSUE THREAD

**Issue by kahanu** [razorjack/quicksand#109]
It took a long time to figure out that, while this is a nice jQuery component, it only works with jQuery 1.8.3.  I tried it with 1.9.1 and 2.0.1 and they both don't work.

It would be nice to get this updated since many of us may have applications that need jQuery versions higher than 1.8.3.

**Comment by ioquatix** [comment]
I'm also having this problem using the package from bower.

**Comment by petulla** [comment]
Same issue here :(

**Comment by ioquatix** [comment]
Installing directly from the git sources worked for me, using bower.

**Comment by razorjack** [comment]
Fixed in recently-released v1.5. Still compatible with jQuery 1.6.1+ but also compatible with 2.0+ and 3.0+.
