### ISSUE TITLE
Use with masonry

### ISSUE THREAD

**Issue by ghost** [razorjack/quicksand#11]
I'm confused.

I see in your script for the demo page that you are using data-value for the menu to display items. However, that isn't in the script for quicksand and I don't see how to make the call for the items. I used a href="#" data-id="group". I hope that's correct.

Additionally, I'm trying to get this to work with jquery masonry with no luck at all.

masonry uses divs and so I replaced li in the call in the head with div, but this did not work. 

When the page loads you see the masonry divs and then they all fade and ease off screen.

Thoughts?

**Comment by aiphee** [comment]
Problem still remains with me, tried brick to brick too wihout much success.

**Comment by razorjack** [comment]
I'm not sure if it's helpful after so many years, it was very difficult to reproduce this issue. But here's my suggestion: use latest version of Quicksand which improves the way plugin interacts with other libraries (`enhancement` function should no longer be needed). Also, try setting `adjustWidth` and `adjustHeight` to `false`. The latest version makes it much easier to use Quicksand on responsive pages. In v1.6.0 the `false` settings forces Quicksand to left width and height of the container alone, which may fix your issue with Masonry.
