### ISSUE TITLE
When filtering, Quicksand doesn't play nice with Wordpress plugin(s)

### ISSUE THREAD

**Issue by ballofpopculture** [razorjack/quicksand#110]
This may be the nature of the beast, but I would love to hear if there is a good work-around:

In this case I am using Quicksand with the Wordpress plugin WP Video Lightbox to display a video portfolio that can be filtered (via Quicksand) by video category.

Usage of WP Video Lightbox is:
<a href="vimeo.com/123456" rel="wp-video-lightbox" title=""><img src="imgurl"></a>

When I first go to the portfolio page everything is fine, but once I click on one of the categories (set up with Quicksand) the images filter correctly, but now none of the links trigger the lightbox.  Checking with Inspect Element shows that the code is exactly the same, but it seems to be operating differently.

Any thoughts?

**Comment by razorjack** [comment]
https://github.com/razorjack/quicksand#integration-with-enhancement-plugins explains how to deal with this exact problem. However, I just released v1.5 where in most cases it resolves the issue automatically, without any need to use `enhancement` function.
