### ISSUE TITLE
Broken responsive gallery issue.

### ISSUE THREAD

**Issue by daugaard47** [razorjack/quicksand#111]
I'm using quicksand to create a gallery for my responsive website and have an issue.

On page load everything scales down as normal, but when I choose one of the categories and the resize the browser window my responsiveness breaks due to an automatic width being added to an inline css element.

See these screen shots to get a better idea of whats happening.
http://daugaard47.com/misc/1.jpg
http://daugaard47.com/misc/2.jpg

How do I remove that width that is being added?

I tried taking out the width but I'm not a JS expert and not sure what I need to take out of the quicksand script to fix this issue. 

Any help would be appreciated. 

Thanks,
Chris

**Comment by razorjack** [comment]
The responsive layout issue is fixed in the latest version v1.6.0. Make sure to set `adjustWidth` option to `false` (or don't use it all, `false` is the default in the latest version).
