### ISSUE TITLE
Problem while using quicksand with pagination

### ISSUE THREAD

**Issue by asad92** [razorjack/quicksand#115]
Hi,
      First of all thanks for providing great jquery plugin for filtering items. I was working today on a project where i have used quicksand It works great on front end. Now i have a problem with pagination. May be i am wrong somewhere however it seems this is an issue with jquery quicksand plugin. I am fetching data from db and adding my category in data-tags for example li data-tags="english"/li li data-tags="arabic"li" it works fine so far and load my categories on top of page. But now i have added pagination on my page and now it only loads first couple of records because of this fact my other categories are not getting load. I want to load all categories once and then paginate through them. Thanks in advance..

**Comment by razorjack** [comment]
The only thing Quicksand does is animation, everything else is up to the web developer, including sorting, filtering and calling Quicksand in the right circumstances. This includes things like data handling like pagination.

To help you with your issue, I see two solutions, both require some custom JavaScript:

1. Add all items to markup. Store all items in a variable you'll later use for filter and sorting. Then, after you sort and filter, render the results and add pagination with jQuery.
2. Do the pagination, sorting and filtering in the backend. Use Ajax call to load the new markup to a variable. Use to ajax-loaded markup as an argument in Quicksand – Quicksand will animate the transition.

The latter should be easier to implement, here's an example of applying Quicksand on data loaded via Ajax: https://razorjack.net/quicksand/demos/ajax.html
