### ISSUE TITLE
Quicksand sorting feature, two different id and Image is coming two time when I select all images

### ISSUE THREAD

**Issue by ajaypanwar092** [razorjack/quicksand#123]
Hi, I am using Quicksand sorting feature but I am facing problem when I am trying to assign two different id to two different Image, the same image is coming two times in landing page i.e when we first initally open page where all the images comes.

For Example I want one image two be in two different category, I have to give different id to both of the images but I want the image to come only one time when we select all images. 

Did I made it clear. 

Here is URL: http://www.sustainabilityconsortium.org/members-test/
And here is Script for sorting:

  // DOMContentLoaded
  $(function() {

```
// bind radiobuttons in the form
var $filterType = $('#filter input[name="type"]');
var $filterSort = $('#filter input[name="sort"]');

// get the first collection
var $applications = $('#applications');

// clone applications to get a second collection
var $data = $applications.clone();

// attempt to call Quicksand on every form change
$filterType.change(function(e) {
  if ($($filterType+':checked').val() == 'all') {
    var $filteredData = $data.find('li');
  } else {
    var $filteredData = $data.find('li[data-type=' + $($filterType+":checked").val() + ']');
  }

  // finally, call quicksand
  $applications.quicksand($filteredData, {
    duration: 800,
    easing: 'linear'
  });

});
```

  });

**Comment by razorjack** [comment]
The provided URL doesn't work, but here's how Quicksand works: it will compare initial and destination collections (and it will determine the identity of each item by it's `data-id`) and animate the transition. If you're seeing duplicates, you need to inspect your target collection and filter it out to the state you'd like to see. Quicksand is pretty dumb, it will take whatever you give to it :) If you don't want to see certain items, make sure to filter them out from the destination collection before calling Quicksand.
