### ISSUE TITLE
Found and fixed a bug when using some responsive widths

### ISSUE THREAD

**Issue by axel20000** [razorjack/quicksand#130]
Hi, i think i found and fixed a bug with quicksand so I wanted to share it in case it helps others.

My container &lt;ul&gt; is inside a bootstrap responsive column. I saw a small but annoying behavior at some window widths. As a use case I had 4 list items &lt;li&gt; in my container and I called quicksand each time window size changed.

At some widths during the animation, these 4  elements animated in a 2x2 formation:
(li) (li)
(li) (li)
but at the end of the animation elements adjusted themselves like this:
(li) (li) (li)
(li)

I noticed the width of my container decreased during animation by 40 pixels and went back to normal at the end, thus animation behaved as described before.

Solution:
I noticed that for some reason $sourceParent.width() and $sourceParent.css("width) had different values, being $sourceParent.width() decreased as I pointed out before. So, at line 90 of quicksand.js I added the following line:
$sourceParent.width(sourceWidth); //sourceWidth has the real width of $sourceParent.css('width')

This way the ugly animation vanished. Hope this helps.

**Comment by axel20000** [comment]
Sorry, I just realised it still happens at some widths.

**Comment by razorjack** [comment]
Please try the latest version (v1.6.0), it fixes the way Quicksand cooperates with responsive widths. Make sure to set `adjustWidth` option to `false`.
