### ISSUE TITLE
Fix please events crush by this solution

### ISSUE THREAD

**Issue by mavlutovr** [razorjack/quicksand#132]
jquery.quicksand.js
line 22:
`var clonedJqueryObject =  jqueryObject.clone(true, true);`

(add "true, true" inside clone() for clone elements with events)
read more here: https://api.jquery.com/clone/

Thank you!

**Comment by razorjack** [comment]
Thanks, that was helpful! Fixed in https://github.com/razorjack/quicksand/commit/bb5e740c0b2b53e9808020114421d8f7565ea5eb, available in v1.5.
