### ISSUE TITLE
Multiple data-types per Item

### ISSUE THREAD

**Issue by loomi** [razorjack/quicksand#21]
Hi razorjack,

love ur work so far, but i have a little question for you. :)
I'd like to show my items in multiple categories, so i tried the following enhancement:

if ($($filterType+':checked').val() == 'all') {
var $filteredData = $data.find('li');
} else {
var $filteredData = $data.find('li[data-type=' + $($filterType+":checked").val() + ']');
var $filteredData = $data.find('li[data-type-2=' + $($filterType+":checked").val() + ']');
var $filteredData = $data.find('li[data-type-3=' + $($filterType+":checked").val() + ']');
}

Template:
li data-id="id-1" data-type="category1" data-type-2="category2" data-type-3="category3"

The problem is, my item is only shown in the 3rd category.
Any suggestions? Thanks in advance.

**Comment by sajumani** [comment]
Hi all,

We had same problem and got exact solution, what you were trying.


if ($('#filter input[name="type"]:checked').val() == 'all') {
                var $filteredData = $data.find('li');
            } else {
                var $filteredData = $data.clone();  // Take a copy of all li elements from UL
                
                $("#filter input[name='type']").each(function(){
                    if (!$(this).is(":checked")) {  // condition for finding unchecked TYPE
                        
                        $filteredData.find('li[data-type="' + $(this).val() + '"]').remove(); // Here we will remove unchecked type matches LI from Variable "$filteredData"
                    }
                });

                $filteredData = $filteredData.find("li"); // Final filtration to find LI
                
            }

**Comment by razorjack** [comment]
Looks like it's resolved, closing :)
