### ISSUE TITLE
Further sorting of the results

### ISSUE THREAD

**Issue by macy** [razorjack/quicksand#22]
Hey

I have set up your excellent quicksand script and its (so far) all working well. My question is this.

In your "Advanced: Sorting one set of HTML (cloning)" example demo, after the person has clicked on the fist option, say "Applications", they can then further sort the items into either size or name (alphabetical order). How can this be modified so that the items are further sorted not by name or size but by another criteria such as they have been in the first step (e.g. first sorted by applications, then the type of application, e.g. game, music apps etc etc?

I am using the code from the main page that makes use of classes to currently identify the correct kind, e.g. app or utility

Would it be possible to have something along the lines of

if (sorting_type == 'game') {
          var $sorted_data = $filtered_data.sorted({
            by: function(v) {
              return all games from the first sorted list of applications
            }
          });
        }

If that does not make any sense, I will happily try and explain further! 

All replays are awesome and very much appreciated!

Many Thanks
Macy

**Comment by razorjack** [comment]
You need to construct your own sorting function if you want to order by two fields. An example is here: https://stackoverflow.com/a/6130014
