### ISSUE TITLE
Why not calling callback on IE6

### ISSUE THREAD

**Issue by dogawaf** [razorjack/quicksand#25]
Hey,

first of all, thanks for this amazing plugin.

but I have a question... why are you not calling the callback function for IE6 ?
It's ok for me to view animation skipped on IE6, but not the callback...

So I use that :

```
   // Replace the collection and quit if IE6
   if ($.browser.msie && $.browser.version.substr(0,1)<7) {
          $sourceParent.html('').append($collection);
          if (typeof callbackFunction == 'function') {
                 callbackFunction.call(this);
          }
          return;
   }
```

**Comment by razorjack** [comment]
IE6 was never supported by this plugin and in current year, nobody uses this browser anymore :)
