### ISSUE TITLE
Trouble with Quicksand function

### ISSUE THREAD

**Issue by nintensity** [razorjack/quicksand#29]
I need some help regarding Quicksand.

I'm trying to initiate Quicksand using lists as buttons but i'm getting awkward CSS style markup when I click on one of the filter links.

Please refer to http://www.nintensity.net/portfolio for the HTML markup, and then http://pastie.org/1166774 for the Javascript Markup.

**Comment by razorjack** [comment]
The issue with responsive layouts is fixed in the latest version of Quicksand (v1.6.0). Please make sure to set `adjustWidth` (or even `adjustHeight`) to `false` so that Quicksand leaves the width/height values alone.
