### ISSUE TITLE
Deep linking and jump to specific category

### ISSUE THREAD

**Issue by jasonkung** [razorjack/quicksand#36]
Is it possible for us to use quicksand in a way when we click a hyperlink on page 1, it'll jump to page 2(w/ quicksand) and selects the relevant category to start first.

Scenario:
On the 'NEWS' page, we see a "Picture A - (Category A)" 
Would like to see it in further detail, we click on it, 
and it jumps to our 'GALLERY' page, and jumps to "Category A" instead of "ALL"

**Comment by razorjack** [comment]
It's definitely possible. Quicksand is an animation-only library, it doesn't stop you from implementing your own interactions that go beyond animations.
