### ISSUE TITLE
integration w/ other jquery plugins / applying callback

### ISSUE THREAD

**Issue by funtoosh** [razorjack/quicksand#40]
gin dobre,
i am trying to get quicksand to work with all of slidetoggle, jplayer and prettyphoto. as i am using code similar to the initial demo, i am unsure a to where & how to apply the callbacks - it must be right at the end, no? the final lines of my code are:

```
        $list.quicksand($sorted_data, $preferences);
        }
      e.preventDefault();
    });
  }); 
});
```

(the current dummy can be seen at weltrettung.org/audiocabbb )

**Comment by razorjack** [comment]
The solution to your exact problem is explained here: https://github.com/razorjack/quicksand#integration-with-enhancement-plugins
