### ISSUE TITLE
Spaces in data-ids

### ISSUE THREAD

**Issue by zfloyd** [razorjack/quicksand#43]
I noticed that I was getting a rawDestElement is undefined error whenever I was filtering down items.  The error was only coming up when I was trying to quicksand one list to a completely different list ([a,b] to [c]).  Something was causing my destElement array inside the $collection.each method to be null.  I started debugging and noticed that if I changed:
destElement = $collection.filter('[' + options.attribute + '=' + $(this).attr(options.attribute) + ']');

to

destElement = $collection.filter('[' + options.attribute + '="' + $(this).attr(options.attribute) + '"]');

that it worked as expected with no javascript error.  The filter function appears to need quotes around the value to be checked if it has spaces.  I'm still partially confused as to why this was not affecting things in a normal use case since it seems like the data should still be filtered out erroneously regardless of whether or not it was in the original list.

**Comment by razorjack** [comment]
It's fixed now: https://github.com/razorjack/quicksand/blob/master/jquery.quicksand.js#L327 :)
