### ISSUE TITLE
Problem with the value passed to Rotation and Scaling pluin

### ISSUE THREAD

**Issue by gubagu** [razorjack/quicksand#57]
Hey Razorjack, 
Great plugin awsome effect I love it !!!

Small issue. I try to use it the plugin with cloning in a small project and discovered that when i use it in combination with the Rotation and Scaling plugin (as you advise on the demo website) it gives and error. The sort functionality works with fading (no scaling) in FF and IE but crashes completely in Chrome. Hereunder more details on the error :

(Chrome 11.0.696.65)
Uncaught TypeError: Cannot call method 'replace' of null                                                  jquery-animate-css-rotate-scale.js : 64

(Firefox 4.0.1)
style is undefined
http://127.0.0.1/quicksandbox/js/jquery-animate-css-rotate-scale.js
Line 64

jquery-1.6.min.js
jquery.quicksand1.2.2.min.js
jquery-animate-css-rotate-scale.js - latest
jquery.easing-1.3.pack.js

The funny part is if  replace all the files above with the jquery-1.4.1-and-plugins.min.js rip from the demo site scaling works as a charm - no error msgs or whatsoever

Does the the js from the demo site contain something different than the files above (except jq1.6 but that shouldn't be an issue. Also tested with 1.4.2 & 1.4.1 and got the same error msg) ?

Any help highly appreciated 
Thanks in advance 

Cheerz,
Guby

**Comment by razorjack** [comment]
Not sure if after so many years its any helpful but I just released v1.5 with different approach to CSS3 transforms :)
