### ISSUE TITLE
Overflow Hidden

### ISSUE THREAD

**Issue by jCrip** [razorjack/quicksand#64]
Hi, please i need your help! I'm using your plugin and is awesome, but i have an issue with a current project, y have de collection with a fixed height with a hidden overflow so only half of the items are visible, and when i filter or sort the collection items , in the animation all the items are visible popping out the hidden overflow, when the animation is over they hide again... i been trying to fix that behavior but i't over me!!!  Please Help!!!!!!!

JC

**Comment by razorjack** [comment]
Thanks for finding the solution!
