### ISSUE TITLE
Quicksand not work with jQuery 1.7.0 ?

### ISSUE THREAD

**Issue by jeremybarbet** [razorjack/quicksand#72]
I would like to know, if it's true that Quicksand don't work with jQuery 1.7.0 or it's my javascript has a problem. If it's Quicksand doesn't work can you fix this problem ?

Sorry, I'm a frenchie, so my english is not perfect.

Best regards.

**Comment by razorjack** [comment]
I just released v1.5. Now it's compatible with jQuery 1.6.1+, jQuery 2.0+ and jQuery 3.0+. The new version modernized approach to CSS3 scaling, you'll have to replace jquery-css-transform.js and jquery-animate-css-rotate-scale.js with https://github.com/razorjack/quicksand/blob/master/jquery.transform2d.js.
