### ISSUE TITLE
Event if $sourceParent is position: relative, it is not used.

### ISSUE THREAD

**Issue by ioquatix** [razorjack/quicksand#81]
Hi,

I suggest that we check the offsetParent of the first-child of $sourceParent, to allow for it to be position: relative/absolute, etc.

Line 93 becomes: `var $correctionParent = $(':first-child', $sourceParent).offsetParent();`

**Comment by razorjack** [comment]
I'm afraid it wouldn't work. Quicksand sets each item's position to `absolute` and moves the items around using `top`/`left`. Having an item with `relative` position would break the plugin.

**Comment by ioquatix** [comment]
Okay, no problem. I can't even remember what this was for :) Thanks for following up.
