### ISSUE TITLE
Iframes losing source url in fancybox window all while in quicksand.

### ISSUE THREAD

**Issue by andywarren** [razorjack/quicksand#86]
Hi we have Quicksand running in a WordPress install.  Each item in Quicksand has a link that will open a Fancybox window.  Everything works as intended including the shuffling, but when a Fancybox window contains and iframe that said iframe loses its source URL if it is Fancyboxed more than once.  I am in huge hopes that someone can point me in the right direction or maybe provide a solution to the problem.  All of this is occurring inside of a Quicksand install.  Thanks, and I'll look forward to some responses!

**Comment by razorjack** [comment]
The latest version (v1.5) resolves this issue automatically. This section explains how to fix it manually or in the previous versions: https://github.com/razorjack/quicksand#integration-with-enhancement-plugins
