### ISSUE TITLE
Windows 8 and IE10 fix

### ISSUE THREAD

**Issue by todorenko** [razorjack/quicksand#89]
No animation in IE10 because the latest version of the browser is not detected. To fix replace this line:
if ($.browser.msie && $.browser.version.substr(0, 1) < 7) {
with this:
if ($.browser.msie && parseInt($.browser.version) < 7) {

Only tested in IE10, don't have access to earlier versions.

**Comment by razorjack** [comment]
Fixed in the latest version of the library, we no longer detect IE – instead we check if the browser is capable of doing CSS3 transforms.
