### ISSUE TITLE
Multiple, independant "galleries"

### ISSUE THREAD

**Issue by adamwoodhouse** [razorjack/quicksand#92]
I'm having issues trying to set up, let's say, 4 independent and individual "galleries" in one page with their own sort options. How may this be done?

Cheers

**Comment by razorjack** [comment]
Quicksand is an animation-only plugin. You can trigger the animation in whatever circumstances you like, you can also filter and sort the items however you want – but this is not what this plugin provides. It only animates for you.

If you'd like to have multiple galleries, you can wrap each one of them in the container, give each container an ID and use the IDs to attach events that react on clicks inside the specific container and use only items inside the container to filter and sort.
