### ISSUE TITLE
Jquery.browser issue

### ISSUE THREAD

**Issue by saruman** [razorjack/quicksand#94]
Hello.  Recenlty, jquery release the latest version of their library, and the script is not working properly... the $.browser.msie is deprecated and removed in jquery version 1.9.

In your code there is a line using that, so, check it out.

Hope you can fix it.

**Comment by razorjack** [comment]
We're no longer using `$.browser.msie`, the issue is fixed. Also, the plugin is now compatible with jQuery 1.6.1+, jQuery 2.0+ and jQuery 3.0+ simultaneously.
