### ISSUE TITLE
How do I manage duplicated images?

### ISSUE THREAD

**Issue by bugsy0206** [razorjack/quicksand#95]
Hi there,

I have used the following JavaScript below, I have tried to alter it so that when the page loads initially, it does not load all lists with all filter types.  The reason I do not want to do this is because I have duplicated images and data for each filter type and therefore I do not want to load all the lists when the page is loaded, I have also hidden the all link list so it is not visible to click.
I would be prefer if I set active to one of the filterOptions, that only that list will be shown when the page is loaded.

Any advise or help is much appreciated.

Cheers,
B

<script>
 $(document).ready(function() {
  // get the action filter option item on page load
 var $filterType = $('#filterOptions li.active a').attr('class');
    
  // get and assign the ourHolder element to the
    // $holder varible for use later
  var $holder = $('ul.ourHolder');

  // clone all items within the pre-assigned $holder element
  var $data = $holder.clone();
 
  // attempt to call Quicksand when a filter option
    // item is clicked
    $('#filterOptions li a').click(function(e) {
        // reset the active class on all the buttons
        $('#filterOptions li').removeClass('active');
        
        // assign the class of the clicked filter option
        // element to our $filterType variable
    var $filterType = $(this).attr('class');
        $(this).parent().addClass('active');
        
        if ($filterType == 'all') {
            // assign all li items to the $filteredData var when
            // the 'All' filter option is clicked
            var $filteredData = $data.find('li');
        } 
      else {
            //find all li elements that have our required $filterType
            // values for the data-type element
        var $filteredData = $data.find('li[data-type=' + $filterType + ']');
        }
        
        // call quicksand and assign transition parameters
        $holder.quicksand($filteredData, {
            duration: 800,
            easing: 'easeInOutQuad'
        });
        return false;
    });
});
</script>

**Comment by razorjack** [comment]
Quicksand is animation-only plugin. It really only animates, it doesn't do anything else – it's up to you to filter/sort and call the animation under the right circumstances.

Here's a hint for your problem: on page load, store all items in a variable. Use the variable as a source of all items. Then, *after* storing the items in the variable, remove the items you don't want to see when the page loads.

And then when use clicks on a filter, use the stored items as your “database” of all items you filter and sort from.
