### ISSUE TITLE
Scaling is not working

### ISSUE THREAD

**Issue by Vishnja** [razorjack/quicksand#99]
Hello! I've read this topic https://github.com/razorjack/quicksand/issues/72 but I'm still unable to make the scaling working (on appearing of objects). This is example of a page http://vishnjasmors.bitte10.in.ua/portfolio/
Thanks, and I'm looking forward to any advices!

**Comment by razorjack** [comment]
This issue was resolved in https://github.com/razorjack/quicksand/issues/72
